### ISSUE TITLE
Telegram Message annoyance

### ISSUE THREAD

**Issue by Minsekt** [nlef/moonraker-telegram-bot#176]
Im having a problem where the bot sends me ![image](https://user-images.githubusercontent.com/103784533/173413967-68a6f29b-c7c5-4266-95a2-a1d11b8109a3.jpeg) this every 5sec. However my progress report is set to 10sec and I've set silent progress to true but it still happens. Happens after the latest update

**Comment by aka13-404** [comment]
Please attach a log when reporting issues.

**Comment by Sirnut** [comment]
This issue started happening to me just now, but I haven't actually updated in a while

[journalctl.txt](https://github.com/nlef/moonraker-telegram-bot/files/8894016/journalctl.txt)
[telegram.log](https://github.com/nlef/moonraker-telegram-bot/files/8894017/telegram.log)

**Comment by aka13-404** [comment]
@Sirnut I deleted your log, since the last version of the bot dumped the token/chatid into the log. If you update, it should be safe again to post logs. But as far as I could see, you had simple internet issues, what does it have to do with notifications?

**Comment by aka13-404** [comment]
@Minsekt 
I have forgotten to updaate the release notes. 

Progress update messages configuration has now been **split into two parts:** `progress_update_message: true` enables the sending of the update message, and `silent_progress: false` to set notification type to silent.

Sorry for the confusion. The thing that you get an update every 5 seconds though, is your configuration.

**Comment by Sirnut** [comment]
@Minsekt Oops, thank you for that. I'm not sure what was causing the notification issues, as yesterday I wasn't having internet issues in the morning (on my desktop at least)

Now that you mention it, I did reboot my router later in the day and haven't had the issue since, but I also haven't printed anything

**Comment by Minsekt** [comment]
@aka13-404 it started happening for me at the last but one update. I then used silent_progress: true as a workaround which got the job done. Now I can't seem to fix it ![image](https://user-images.githubusercontent.com/103784533/173631501-8a60fe96-4d57-4d39-9fba-c93d991127ed.jpeg)

When using progress_update_message I get an error

**Comment by Minsekt** [comment]
Removed the bot and did a clean install, now it's working.

**Comment by Sirnut** [comment]
@Minsekt I'll give that a shot too

**Comment by aka13-404** [comment]
@Minsekt We had a bug with the `progress_update_message:´ option. I have just updated the wiki, and nlef rolled out a fix for the config checker. When setting `progress_update_message: false´ in the gui section, it should now work as expected, at least it does so for me. Please let me know how it works out.

**Comment by Minsekt** [comment]
> @Minsekt We had a bug with the `progress_update_message:´ option. I have just updated the wiki, and nlef rolled out a fix for the config checker. When setting `progress_update_message: false´ in the gui section, it should now work as expected, at least it does so for me. Please let me know how it works out.

yes its working now. thanks!

**Comment by Sirnut** [comment]
So after a fresh install today with "silent_status: true" I still get this message

This wasn't happening for months. Why would it all of a sudden have started without prior to any updates

**Comment by Sirnut** [comment]
I am unsure whether this plays a role, but I manually install my bot and then add it to the moonraker update manager. I back my klipper_config up to a public repository, so I cannot keep the telegram.conf inside there for security reasons

**Comment by aka13-404** [comment]
Because this has nothing to do with getting the message as per this ticket, changelog or wiki entries.
